default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: giorg
  password: password
  host: localhost
  port: 5432


development:
  <<: *default
  database: todos_api_saas_development
test:
  <<: *default
  database: todos_api_saas_test

production:
  <<: *default
  database: todos_api_saas_production